# rules that have both warning and error levels, can set just the warning level
# implicitly

line_length: 200
# they can set both implicitly with an array

disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - trailing_comma
  - multiple_closures_with_trailing_closure
  - xctfail_message
  - legacy_random
  - reduce_boolean
  - for_where
  - first_where
  - is_disjoint
variable_name:
     allowed_symbols: "_"
